### PR TITLE
More options on the command line

### PR DESCRIPTION
**Pull request by hanesbarbosa**
I created two straightfoward options due to my needs of restricting results.

### CODE REVIEW

**Comment by hanesbarbosa** [comment]
You can consider an work in progress, but we can take advantage of these few improvements.

**Comment by davidwilliam** [comment]
@hanesbarbosa Como deveria aparecer o texto de help? Tb não vi o menu. Pesquisei com e sem critério e não vi mudança.

**Comment by hanesbarbosa** [comment]
Try using just the command without any options or urls.

**Comment by davidwilliam** [comment]
That's what I did

**Pull request closed without merging**
